<?php

namespace AppBundle\Repository;

/**
 * AnalysisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalysisRepository extends \Doctrine\ORM\EntityRepository
{
}
