<?php

namespace AppBundle\Repository;

/**
 * LyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyceeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSchoolOrderByDepartment(?string $department)
    {
        $qb = $this->createQueryBuilder('s')
            ->join('s.department', 'd');
        if ($department) {
            $qb->where('d.name = :department')
                ->setParameter(':department', $department);
        }

        $qb->orderBy('d.shortCode','ASC')
            ->addOrderBy('s.name', 'ASC')
            ;
        return $qb->getQuery()->getResult();
    }
}
