<?php

namespace AppBundle\Repository;

/**
 * LyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyceeRepository extends \Doctrine\ORM\EntityRepository
{
}
