<?php

namespace AppBundle\Repository;

/**
 * LyceeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyceeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSchoolOrderByDepartment(string $department)
    {
        if (empty($department)) {
            return $this->createQueryBuilder('s')
                ->join('s.department', 'd')
                ->where('s.department = d.id')
                ->addOrderBy('d.shortCode', 'ASC')
                ->addOrderBy('s.name', 'ASC')
                ->getQuery()
                ->getResult();
        }
        return $this->createQueryBuilder('s')
            ->join('s.department', 'd')
            ->where('s.department = d.id')
            ->andWhere('d.name = :department')
            ->setParameter(':department', $department)
            ->addOrderBy('s.name', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
