<?php

namespace AppBundle\Repository;

/**
 * MetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierRepository extends \Doctrine\ORM\EntityRepository
{
}
