<?php

namespace AppBundle\Repository;

/**
 * SheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SheetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSheetsByDepartment(string $department)
    {
        return $this->createQueryBuilder('s')
            ->join('s.user', 'u')
            ->join('u.lycee','l')
            ->join('l.department','d')
            ->where('d.name = :department')
            ->setParameter(':department', $department)
            ->getQuery()
            ->getResult();
    }
}
